/**
 * Fallback dataset for PSX Market News & Corporate Disclosures.
 * Adheres 100% to backend FastAPI schemas:
 * - NewsArticleResponse
 * - NewsListResponse
 * - SourcesResponse
 * - NewsRefreshStatusResponse
 */

export const FALLBACK_MARKET_STATUS = {
  market_open: true,
  is_ingestion_allowed: true,
  current_time_pkt: new Date().toISOString(),
  session: 'Continuous Trading',
  market_window: '09:15 - 15:30 PKT',
  next_ingestion_window: '09:15 PKT',
};

export const FALLBACK_SOURCES = {
  sources: [
    {
      key: 'psx',
      name: 'PSX Official Announcements',
      type: 'official',
      last_success_at: new Date(Date.now() - 6 * 60000).toISOString(),
      last_error: null,
      consecutive_failures: 0,
      healthy: true,
    },
    {
      key: 'secp',
      name: 'SECP Regulatory Notices',
      type: 'official',
      last_success_at: new Date(Date.now() - 14 * 60000).toISOString(),
      last_error: null,
      consecutive_failures: 0,
      healthy: true,
    },
    {
      key: 'sbp',
      name: 'State Bank of Pakistan',
      type: 'official',
      last_success_at: new Date(Date.now() - 22 * 60000).toISOString(),
      last_error: null,
      consecutive_failures: 0,
      healthy: true,
    },
    {
      key: 'ogra',
      name: 'OGRA Petroleum & Gas',
      type: 'official',
      last_success_at: new Date(Date.now() - 35 * 60000).toISOString(),
      last_error: null,
      consecutive_failures: 0,
      healthy: true,
    },
    {
      key: 'fbr_mof',
      name: 'FBR & Ministry of Finance',
      type: 'official',
      last_success_at: new Date(Date.now() - 48 * 60000).toISOString(),
      last_error: null,
      consecutive_failures: 0,
      healthy: true,
    },
    {
      key: 'business_recorder',
      name: 'Business Recorder',
      type: 'news',
      last_success_at: new Date(Date.now() - 8 * 60000).toISOString(),
      last_error: null,
      consecutive_failures: 0,
      healthy: true,
    },
    {
      key: 'dawn',
      name: 'Dawn Business',
      type: 'news',
      last_success_at: new Date(Date.now() - 12 * 60000).toISOString(),
      last_error: null,
      consecutive_failures: 0,
      healthy: true,
    },
    {
      key: 'mettis',
      name: 'Mettis Global',
      type: 'news',
      last_success_at: new Date(Date.now() - 5 * 60000).toISOString(),
      last_error: null,
      consecutive_failures: 0,
      healthy: true,
    },
  ],
};

export const FALLBACK_ARTICLES = [
  {
    id: 'psx_berg_financial_result_2026',
    title: 'Financial Result for the Year Ended June 30, 2026',
    url: 'https://dps.psx.com.pk/announcements',
    external_url: 'https://dps.psx.com.pk/announcements',
    source: {
      key: 'psx',
      name: 'PSX Official Announcements',
      type: 'official',
    },
    is_official: true,
    summary: 'Berger Paints Pakistan Limited reported revenue of PKR 9.18 billion (+2.6% YoY) and net profit after taxation of PKR 309 million (+3.6% YoY) for the year ended June 30, 2026. The Board recommended a final cash dividend of PKR 5.00 per share (50%). EPS improved to PKR 12.60.',
    symbols: [{ symbol: 'BERG', name: 'Berger Paints Pakistan Limited' }],
    event_type: 'financial_result',
    sentiment: {
      label: 'bullish',
      score: 0.88,
      method: 'finbert',
    },
    impact_score: 92,
    published_at: new Date(Date.now() - 25 * 60000).toISOString(),
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'psx_sys_q2_consolidated_results',
    title: 'Systems Limited Reports 28% Profit Surge in Q2 2026 Consolidated Results',
    url: 'https://dps.psx.com.pk/announcements',
    external_url: 'https://dps.psx.com.pk/announcements',
    source: {
      key: 'psx',
      name: 'PSX Official Announcements',
      type: 'official',
    },
    is_official: true,
    summary: 'Systems Limited (SYS) announced consolidated net revenue of PKR 31.4 billion for Q2 2026, driven by North American and Middle Eastern export contracts. Export revenue climbed 34% while gross margins expanded to 31.8%.',
    symbols: [{ symbol: 'SYS', name: 'Systems Limited' }],
    event_type: 'financial_result',
    sentiment: {
      label: 'bullish',
      score: 0.86,
      method: 'finbert',
    },
    impact_score: 89,
    published_at: new Date(Date.now() - 55 * 60000).toISOString(),
    created_at: new Date(Date.now() - 55 * 60000).toISOString(),
  },
  {
    id: 'psx_ogdc_discovery_tolanj_west',
    title: 'Major Gas & Condensate Hydrocarbon Discovery at Tolanj West-02 Well',
    url: 'https://dps.psx.com.pk/announcements',
    external_url: 'https://dps.psx.com.pk/announcements',
    source: {
      key: 'psx',
      name: 'PSX Official Announcements',
      type: 'official',
    },
    is_official: true,
    summary: 'Oil & Gas Development Company Limited (OGDC), operator of the Tal Block joint venture, has discovered significant gas and condensate reserves at Tolanj West-02. Production testing demonstrated 23.5 MMSCFD gas and 540 BPD condensate.',
    symbols: [
      { symbol: 'OGDC', name: 'Oil & Gas Development Company Limited' },
      { symbol: 'POL', name: 'Pakistan Oilfields Limited' },
      { symbol: 'PPL', name: 'Pakistan Petroleum Limited' },
    ],
    event_type: 'announcement',
    sentiment: {
      label: 'bullish',
      score: 0.92,
      method: 'finbert',
    },
    impact_score: 95,
    published_at: new Date(Date.now() - 110 * 60000).toISOString(),
    created_at: new Date(Date.now() - 110 * 60000).toISOString(),
  },
  {
    id: 'psx_hubc_interim_dividend_meeting',
    title: 'Board of Directors Meeting Scheduled to Consider 1st Interim Dividend',
    url: 'https://dps.psx.com.pk/announcements',
    external_url: 'https://dps.psx.com.pk/announcements',
    source: {
      key: 'psx',
      name: 'PSX Official Announcements',
      type: 'official',
    },
    is_official: true,
    summary: 'The Hub Power Company Limited (HUBC) informed the exchange that a meeting of its Board of Directors will be held on Thursday to review quarterly accounts and consider declaration of an interim cash dividend for shareholders.',
    symbols: [{ symbol: 'HUBC', name: 'The Hub Power Company Limited' }],
    event_type: 'board_meeting',
    sentiment: {
      label: 'neutral',
      score: 0.52,
      method: 'finbert',
    },
    impact_score: 74,
    published_at: new Date(Date.now() - 180 * 60000).toISOString(),
    created_at: new Date(Date.now() - 180 * 60000).toISOString(),
  },
  {
    id: 'psx_engro_thermal_restructuring',
    title: 'Engro Corporation Completes Thermal Energy Division Restructuring',
    url: 'https://dps.psx.com.pk/announcements',
    external_url: 'https://dps.psx.com.pk/announcements',
    source: {
      key: 'psx',
      name: 'PSX Official Announcements',
      type: 'official',
    },
    is_official: true,
    summary: 'Engro Corporation Limited (ENGRO) has executed the formal divestment and restructuring of its thermal energy assets, reallocating capital into renewables, telecommunications infrastructure, and high-margin export sectors.',
    symbols: [{ symbol: 'ENGRO', name: 'Engro Corporation Limited' }],
    event_type: 'announcement',
    sentiment: {
      label: 'bullish',
      score: 0.82,
      method: 'finbert',
    },
    impact_score: 86,
    published_at: new Date(Date.now() - 240 * 60000).toISOString(),
    created_at: new Date(Date.now() - 240 * 60000).toISOString(),
  },
  {
    id: 'psx_hbl_insider_shareholding',
    title: 'Disclosure of Interest by Director / Executive in Company Shares',
    url: 'https://dps.psx.com.pk/announcements',
    external_url: 'https://dps.psx.com.pk/announcements',
    source: {
      key: 'psx',
      name: 'PSX Official Announcements',
      type: 'official',
    },
    is_official: true,
    summary: 'Habib Bank Limited (HBL) disclosed that a sponsor executive acquired 150,000 ordinary shares at an average execution price of PKR 128.45 via the regular PSX market session, in compliance with SECP insider regulations.',
    symbols: [{ symbol: 'HBL', name: 'Habib Bank Limited' }],
    event_type: 'insider_trading',
    sentiment: {
      label: 'neutral',
      score: 0.60,
      method: 'finbert',
    },
    impact_score: 68,
    published_at: new Date(Date.now() - 320 * 60000).toISOString(),
    created_at: new Date(Date.now() - 320 * 60000).toISOString(),
  },
  {
    id: 'dawn_sbp_monetary_policy_review',
    title: 'State Bank Maintains Policy Rate as Inflation Cools to 9.2% YoY',
    url: 'https://www.dawn.com/business',
    external_url: 'https://www.dawn.com/business',
    source: {
      key: 'dawn',
      name: 'Dawn Business',
      type: 'news',
    },
    is_official: false,
    summary: 'The Monetary Policy Committee of the State Bank of Pakistan observed positive real interest rate trajectories and continuing foreign exchange accretion, supporting monetary stability across commercial banking and industrial equities.',
    symbols: [
      { symbol: 'MCB', name: 'MCB Bank Limited' },
      { symbol: 'MEBL', name: 'Meezan Bank Limited' },
      { symbol: 'UBL', name: 'United Bank Limited' },
    ],
    event_type: 'market_update',
    sentiment: {
      label: 'bullish',
      score: 0.79,
      method: 'finbert',
    },
    impact_score: 94,
    published_at: new Date(Date.now() - 410 * 60000).toISOString(),
    created_at: new Date(Date.now() - 410 * 60000).toISOString(),
  },
  {
    id: 'br_pso_circular_debt_allocation',
    title: 'ECC Approves PKR 65 Billion Settlement Tranche for Energy Sector Liquidity',
    url: 'https://www.brecorder.com',
    external_url: 'https://www.brecorder.com',
    source: {
      key: 'business_recorder',
      name: 'Business Recorder',
      type: 'news',
    },
    is_official: false,
    summary: 'The Economic Coordination Committee approved a targeted disbursement package for PSO, SNGPL, and SSGC to clear overdue circular receivables and ensure uninterrupted seasonal fuel supply.',
    symbols: [
      { symbol: 'PSO', name: 'Pakistan State Oil Company Limited' },
      { symbol: 'SNGP', name: 'Sui Northern Gas Pipelines Limited' },
      { symbol: 'SSGC', name: 'Sui Southern Gas Company Limited' },
    ],
    event_type: 'market_update',
    sentiment: {
      label: 'bullish',
      score: 0.84,
      method: 'finbert',
    },
    impact_score: 91,
    published_at: new Date(Date.now() - 500 * 60000).toISOString(),
    created_at: new Date(Date.now() - 500 * 60000).toISOString(),
  },
  {
    id: 'psx_luck_cement_line_commissioning',
    title: 'Commercial Production Commences at Pezu Line-3 Cement Unit',
    url: 'https://dps.psx.com.pk/announcements',
    external_url: 'https://dps.psx.com.pk/announcements',
    source: {
      key: 'psx',
      name: 'PSX Official Announcements',
      type: 'official',
    },
    is_official: true,
    summary: 'Lucky Cement Limited (LUCK) successfully initiated commercial operations at its 3.15 MTPA state-of-the-art expansion line in Pezu, expanding overall domestic cement and clinker manufacturing capacity to 15.3 MTPA.',
    symbols: [{ symbol: 'LUCK', name: 'Lucky Cement Limited' }],
    event_type: 'announcement',
    sentiment: {
      label: 'bullish',
      score: 0.89,
      method: 'finbert',
    },
    impact_score: 87,
    published_at: new Date(Date.now() - 620 * 60000).toISOString(),
    created_at: new Date(Date.now() - 620 * 60000).toISOString(),
  },
  {
    id: 'mettis_efert_fertilizer_demand',
    title: 'Fertilizer Offtake Jumps 14% on Winter Wheat Sowing Surge',
    url: 'https://mettisglobal.news',
    external_url: 'https://mettisglobal.news',
    source: {
      key: 'mettis',
      name: 'Mettis Global',
      type: 'news',
    },
    is_official: false,
    summary: 'Urea and DAP dispatches registered strong seasonal uptake across Punjab and Sindh agricultural belts, bolstering cash flow projections for EFERT, FFC, and FFBL.',
    symbols: [
      { symbol: 'EFERT', name: 'Engro Fertilizers Limited' },
      { symbol: 'FFC', name: 'Fauji Fertilizer Company Limited' },
      { symbol: 'FFBL', name: 'Fauji Fertilizer Bin Qasim Limited' },
    ],
    event_type: 'market_update',
    sentiment: {
      label: 'bullish',
      score: 0.81,
      method: 'finbert',
    },
    impact_score: 83,
    published_at: new Date(Date.now() - 740 * 60000).toISOString(),
    created_at: new Date(Date.now() - 740 * 60000).toISOString(),
  },
  {
    id: 'psx_secp_digital_asset_guidelines',
    title: 'SECP Issues Updated Corporate Governance & ESG Disclosure Framework',
    url: 'https://dps.psx.com.pk/announcements',
    external_url: 'https://dps.psx.com.pk/announcements',
    source: {
      key: 'secp',
      name: 'SECP Regulatory Notices',
      type: 'official',
    },
    is_official: true,
    summary: 'The Securities and Exchange Commission of Pakistan released updated compliance guidelines for PSX-listed public entities covering mandatory climate disclosures, board diversity metrics, and digital proxy voting mechanisms.',
    symbols: [],
    event_type: 'regulatory_notice',
    sentiment: {
      label: 'neutral',
      score: 0.50,
      method: 'eps_rule',
    },
    impact_score: 75,
    published_at: new Date(Date.now() - 860 * 60000).toISOString(),
    created_at: new Date(Date.now() - 860 * 60000).toISOString(),
  },
  {
    id: 'psx_airlink_smartphones_export',
    title: 'Air Link Communication Secures Regional Smartphone Export Mandate',
    url: 'https://dps.psx.com.pk/announcements',
    external_url: 'https://dps.psx.com.pk/announcements',
    source: {
      key: 'psx',
      name: 'PSX Official Announcements',
      type: 'official',
    },
    is_official: true,
    summary: 'Air Link Communication Limited (AIRLINK) finalized an international contract to export 250,000 locally manufactured smartphone handsets to African and Central Asian markets over the next two fiscal quarters.',
    symbols: [{ symbol: 'AIRLINK', name: 'Air Link Communication Limited' }],
    event_type: 'announcement',
    sentiment: {
      label: 'bullish',
      score: 0.87,
      method: 'finbert',
    },
    impact_score: 85,
    published_at: new Date(Date.now() - 980 * 60000).toISOString(),
    created_at: new Date(Date.now() - 980 * 60000).toISOString(),
  },
];

