global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: basarat-api
    metrics_path: /metrics
    http_headers:
      Host:
        values:
          - ${PROMETHEUS_METRICS_HOST_HEADER}
    basic_auth:
      username: ${PROMETHEUS_METRICS_USERNAME}
      password: ${PROMETHEUS_METRICS_PASSWORD}
    static_configs:
      - targets:
          - app:8000
