"""add phone to users

Revision ID: 086966b29484
Revises: 12ad0678d7ce
Create Date: 2026-09-13 14:50:47.087916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086966b29484'
down_revision = '12ad0678d7ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###