"""add risk profiles table

Revision ID: 0ff4677b014d
Revises: 086966b29484
Create Date: 2026-09-13 15:07:38.444235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ff4677b014d'
down_revision = '086966b29484'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('risk_tolerance', sa.Enum('conservative', 'moderate', 'aggressive', name='risk_tolerance_enum'), nullable=False),
    sa.Column('sector_preferences', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('investment_horizon', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_profiles_user_id'), 'risk_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_profiles_user_id'), table_name='risk_profiles')
    op.drop_table('risk_profiles')
    # ### end Alembic commands ###